export { Header } from "./Header"
export { Sidebar } from "./Sidebar"
export { CustomerDetail } from "./CustomerDetail"
export { StatsRow } from "./StatsRow"
export { InsightTimeline } from "./InsightTimeline"
export { WholeStory } from "./WholeStory"
export { Dashboard } from "./Dashboard"
export { AddCustomerModal, type CustomerFormData } from "./AddCustomerModal"
export { AddInsightModal, type InsightFormData } from "./AddInsightModal"
export { CheckInModal, type CheckInNotes } from "./CheckInModal"
